(function(g){var window=this;'use strict';var qkb=function(a,b){a.eb("onAutonavCoundownStarted",b)},l5=function(a,b,c){g.sp(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.lh(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.fQ&&(b.lengthText?(e=b.lengthText||null,f=b.jy||null):b.lengthSeconds&&(e=g.Ly(b.lengthSeconds),f=g.Ly(b.lengthSeconds,!0)));var h=!!d;d=h&&g.dQ(d).type==="RD";var l=b instanceof g.fQ?b.isLivePlayback:null,m=b instanceof g.fQ?b.isUpcoming:null,n=b.author,p=b.shortViewCount,q=b.publishedTimeText,r=[],t=[];n&&r.push(n);p&&(r.push(p),t.push(p));q&&t.push(q);c={title:b.title,author:n,author_and_views:r.join(" \u2022 "),aria_label:b.ariaLabel||
g.CE("Xem $TITLE",{TITLE:b.title}),duration:e,timestamp:f,url:b.Ol(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:t.join(" \u2022 "),autoplayAlternativeHeader:b.Mt};b instanceof g.eQ&&(c.playlist_length=b.playlistLength);a.update(c)},m5=function(a){var b=a.U(),c=b.D;
g.S.call(this,{I:"a",S:"ytp-autonav-suggestion-card",X:{href:"{{url}}",target:c?b.W:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{I:"div",Ka:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],X:{style:"{{background}}"},V:[{I:"div",X:{"aria-label":"{{timestamp}}"},Ka:["ytp-autonav-timestamp"],va:"{{duration}}"},{I:"div",Ka:["ytp-autonav-live-stamp"],va:"Tr\u1ef1c ti\u1ebfp"},
{I:"div",Ka:["ytp-autonav-upcoming-stamp"],va:"S\u1eafp di\u1ec5n ra"},{I:"div",S:"ytp-autonav-list-overlay",V:[{I:"div",S:"ytp-autonav-mix-text",va:"Tuy\u1ec3n t\u1eadp"},{I:"div",S:"ytp-autonav-mix-icon"}]}]},{I:"div",Ka:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],va:"{{title}}"},{I:"div",Ka:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],va:"{{author}}"},{I:"div",Ka:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],va:"{{views_and_publish_time}}"}]});
this.J=a;this.suggestion=null;this.j=c;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},n5=function(a,b){b=b===void 0?!1:b;
g.S.call(this,{I:"div",S:"ytp-autonav-endscreen-countdown-overlay"});var c=this;this.K=b;this.cancelCommand=this.G=void 0;this.C=0;this.container=new g.S({I:"div",S:"ytp-autonav-endscreen-countdown-container"});g.P(this,this.container);this.container.Ha(this.element);b=a.U();var d=b.D;this.J=a;this.suggestion=null;this.onVideoDataChange("newdata",this.J.getVideoData());this.T(a,"videodatachange",this.onVideoDataChange);this.j=new g.S({I:"div",S:"ytp-autonav-endscreen-upnext-container",X:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{I:"div",S:"ytp-autonav-endscreen-upnext-header"},{I:"div",S:"ytp-autonav-endscreen-upnext-alternative-header",va:"{{autoplayAlternativeHeader}}"},{I:"a",S:"ytp-autonav-endscreen-link-container",X:{href:"{{url}}",target:d?b.W:""},V:[{I:"div",S:"ytp-autonav-endscreen-upnext-thumbnail",X:{style:"{{background}}"},V:[{I:"div",X:{"aria-label":"{{timestamp}}"},Ka:["ytp-autonav-timestamp"],
va:"{{duration}}"},{I:"div",Ka:["ytp-autonav-live-stamp"],va:"Tr\u1ef1c ti\u1ebfp"},{I:"div",Ka:["ytp-autonav-upcoming-stamp"],va:"S\u1eafp di\u1ec5n ra"}]},{I:"div",S:"ytp-autonav-endscreen-video-info",V:[{I:"div",S:"ytp-autonav-endscreen-premium-badge"},{I:"div",S:"ytp-autonav-endscreen-upnext-title",va:"{{title}}"},{I:"div",S:"ytp-autonav-endscreen-upnext-author",va:"{{author}}"},{I:"div",S:"ytp-autonav-view-and-date",va:"{{views_and_publish_time}}"},{I:"div",S:"ytp-autonav-author-and-view",va:"{{author_and_views}}"}]}]}]});
g.P(this,this.j);this.j.Ha(this.container.element);d||this.T(this.j.Da("ytp-autonav-endscreen-link-container"),"click",this.vV);this.J.createClientVe(this.container.element,this,115127);this.J.createClientVe(this.j.Da("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.S({I:"div",S:"ytp-autonav-overlay"});g.P(this,this.overlay);this.overlay.Ha(this.container.element);this.B=new g.S({I:"div",S:"ytp-autonav-endscreen-button-container"});g.P(this,this.B);this.B.Ha(this.container.element);
this.cancelButton=new g.S({I:"button",Ka:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",b.L("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{"aria-label":"H\u1ee7y t\u1ef1 \u0111\u1ed9ng ph\u00e1t"},va:"H\u1ee7y"});g.P(this,this.cancelButton);this.cancelButton.Ha(this.B.element);this.cancelButton.listen("click",this.l5,this);this.J.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.S({I:"a",Ka:["ytp-autonav-endscreen-upnext-button",
"ytp-autonav-endscreen-upnext-play-button",b.L("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{href:"{{url}}",role:"button","aria-label":"Ph\u00e1t video ti\u1ebfp theo"},va:"Ph\u00e1t ngay"});g.P(this,this.playButton);this.playButton.Ha(this.B.element);this.playButton.listen("click",this.vV,this);this.J.L("web_player_autonav_next_button_renderer")?(this.J.createServerVe(this.playButton.element,this.playButton,!0),(b=this.J.getVideoData())&&rkb(this,b)):this.J.createClientVe(this.playButton.element,
this,115130);this.D=new g.gp(function(){skb(c)},500);
g.P(this,this.D);this.uV();this.T(a,"autonavvisibility",this.uV);this.J.L("web_autonav_color_transition")&&(this.T(a,"autonavchange",this.k5),this.T(a,"onAutonavCoundownStarted",this.Waa))},o5=function(a){var b=a.J.Fo(!0,a.J.isFullscreen());
g.sp(a.container.element,"ytp-autonav-endscreen-small-mode",a.Sg(b));g.sp(a.container.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.jN);g.sp(a.J.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.J.Hf());g.sp(a.J.getRootNode(),"countdown-running",a.Vl());g.sp(a.container.element,"ytp-player-content",a.J.Hf());g.um(a.overlay.element,{width:b.width+"px"});if(!a.Vl()){a.J.Hf()?tkb(a,Math.round(ukb(a)/1E3)):tkb(a);b=!!a.suggestion&&!!a.suggestion.Mt;var c=a.J.Hf()||!b;
g.sp(a.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!c&&b);g.sp(a.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.zx(a.B,a.J.Hf());g.sp(a.element,"ytp-enable-w2w-color-transitions",vkb(a))}},skb=function(a){var b=ukb(a),c=Math,d=c.min;
var e=a.C?Date.now()-a.C:0;c=d.call(c,e,b);tkb(a,Math.ceil((b-c)/1E3));b-c<=500&&a.Vl()?a.select(!0):a.Vl()&&a.D.start()},ukb=function(a){if(a.J.isFullscreen()){var b;
a=(b=a.J.getVideoData())==null?void 0:b.bE;return a===-1||a===void 0?8E3:a}return a.J.du()>=0?a.J.du():g.zD(a.J.U().experiments,"autoplay_time")||1E4},rkb=function(a,b){a.J.L("web_player_autonav_next_button_renderer");
b=b.P4;a.G=b==null?void 0:b.navigationEndpoint;b=b==null?void 0:b.trackingParams;a.playButton&&b&&a.J.setTrackingParams(a.playButton.element,b)},vkb=function(a){var b;
return!((b=a.J.getVideoData())==null||!b.watchToWatchTransitionRenderer)},tkb=function(a,b){b=b===void 0?-1:b;
a=a.j.Da("ytp-autonav-endscreen-upnext-header");g.ih(a);if(b>=0){b=String(b);var c="Video ti\u1ebfp theo sau $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Video ti\u1ebfp theo sau $SECONDS".indexOf(c);if(d>=0){a.appendChild(g.gh("Video ti\u1ebfp theo sau $SECONDS".slice(0,d)));var e=g.fh("span");g.mp(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.mh(e,b);a.appendChild(e);a.appendChild(g.gh("Video ti\u1ebfp theo sau $SECONDS".slice(d+c.length)));return}}g.mh(a,"Ti\u1ebfp theo")},p5=
function(a,b){g.S.call(this,{I:"div",
Ka:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},q5=function(a){g.S.call(this,{I:"div",
Ka:["ytp-upnext","ytp-player-content"],X:{"aria-label":"{{aria_label}}"},V:[{I:"div",S:"ytp-cued-thumbnail-overlay-image",X:{style:"{{background}}"}},{I:"span",S:"ytp-upnext-top",V:[{I:"span",S:"ytp-upnext-header",va:"Ti\u1ebfp theo"},{I:"span",S:"ytp-upnext-title",va:"{{title}}"},{I:"span",S:"ytp-upnext-author",va:"{{author}}"}]},{I:"a",S:"ytp-upnext-autoplay-icon",X:{role:"button",href:"{{url}}","aria-label":"Ph\u00e1t video ti\u1ebfp theo"},V:[{I:"svg",X:{height:"100%",version:"1.1",viewBox:"0 0 72 72",
width:"100%"},V:[{I:"circle",S:"ytp-svg-autoplay-circle",X:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{I:"circle",S:"ytp-svg-autoplay-ring",X:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{I:"path",S:"ytp-svg-fill",X:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{I:"span",S:"ytp-upnext-bottom",V:[{I:"span",S:"ytp-upnext-cancel"},{I:"span",S:"ytp-upnext-paused",
va:"T\u1ef1 \u0111\u1ed9ng ph\u00e1t b\u1ecb t\u1ea1m d\u1eebng"}]}]});this.api=a;this.cancelButton=null;this.G=this.Da("ytp-svg-autoplay-ring");this.C=this.notification=this.j=this.suggestion=null;this.D=new g.gp(this.IJ,5E3,this);this.B=0;var b=this.Da("ytp-upnext-cancel");this.cancelButton=new g.S({I:"button",Ka:["ytp-upnext-cancel-button","ytp-button"],X:{tabindex:"0","aria-label":"H\u1ee7y t\u1ef1 \u0111\u1ed9ng ph\u00e1t"},va:"H\u1ee7y"});g.P(this,this.cancelButton);this.cancelButton.listen("click",
this.m5,this);this.cancelButton.Ha(b);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,this,115129);g.P(this,this.D);this.api.createClientVe(this.element,this,18788);b=this.Da("ytp-upnext-autoplay-icon");this.T(b,"click",this.n5);this.api.createClientVe(b,this,115130);this.wV();this.T(a,"autonavvisibility",this.wV);this.T(a,"mdxnowautoplaying",this.Lba);this.T(a,"mdxautoplaycanceled",this.Mba);g.sp(this.element,"ytp-upnext-mobile",this.api.U().B)},wkb=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=(c=a.api.getVideoData())==null?void 0:c.bE;return a===-1||a===void 0?8E3:a}return a.api.du()>=0?a.api.du():g.zD(a.api.U().experiments,"autoplay_time")||1E4},xkb=function(a,b){b=wkb(a,b);
var c=Math,d=c.min;var e=(0,g.Kt)()-a.B;c=d.call(c,e,b);b=b===0?1:Math.min(c/b,1);a.G.setAttribute("stroke-dashoffset",""+-211*(b+1));b>=1&&a.Vl()&&a.api.getPresentingPlayerType()!==3?a.select(!0):a.Vl()&&a.j.start()},r5=function(a){p5.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.S({I:"div",S:"ytp-suggestion-panel",V:[{I:"div",Ka:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],va:"Video kh\u00e1c"}]});this.N=new g.S({I:"div",S:"ytp-suggestions-container"});this.videos=[];this.C=null;this.G=this.K=!1;this.B=new n5(this.player);g.P(this,this.B);this.B.Ha(this.element);a.getVideoData().zf?this.j=this.B:(this.j=new q5(a),g.DS(this.player,this.j.element,4),g.P(this,this.j));this.overlay=new g.S({I:"div",
S:"ytp-autonav-overlay-cancelled-state"});g.P(this,this.overlay);this.overlay.Ha(this.element);this.D=new g.PF(this);g.P(this,this.D);g.P(this,this.table);this.table.Ha(this.element);this.table.show();g.P(this,this.N);this.N.Ha(this.table.element);this.hide()},s5=function(a){var b=a.Hf();
b!==a.G&&(a.G=b,a.player.publish("autonavvisibility"),a.G?(a.B!==a.j&&a.B.hide(),a.table.hide()):(a.B!==a.j&&a.B.show(),a.table.show()))},t5=function(a,b){g.S.call(this,{I:"button",
Ka:["ytp-watch-on-youtube-button","ytp-button"],va:"{{content}}"});this.J=a;this.buttonType=this.buttonType=b;this.M2();this.buttonType===2&&g.op(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.M2);g.zx(this,!0)},u5=function(a,b){p5.call(this,a,"embeds-lite-endscreen");
this.J=a;this.Qe=b;this.J.createClientVe(this.element,this,156943);this.watchButton=new t5(a,2);g.P(this,this.watchButton);this.watchButton.Ha(this.element);this.hide()},ykb=function(a){p5.call(this,a,"subscribecard-endscreen");
this.j=new g.S({I:"div",S:"ytp-subscribe-card",V:[{I:"img",S:"ytp-author-image",X:{src:"{{profilePicture}}"}},{I:"div",S:"ytp-subscribe-card-right",V:[{I:"div",S:"ytp-author-name",va:"{{author}}"},{I:"div",S:"html5-subscribe-button-container"}]}]});g.P(this,this.j);this.j.Ha(this.element);var b=a.getVideoData();this.subscribeButton=new g.CY("\u0110\u0103ng k\u00fd",null,"H\u1ee7y \u0111\u0103ng k\u00fd",null,!0,!1,b.xm,b.subscribed,"trailer-endscreen",null,a,!1);g.P(this,this.subscribeButton);this.subscribeButton.Ha(this.j.Da("html5-subscribe-button-container"));
this.T(a,"videodatachange",this.Ra);this.Ra();this.hide()},v5=function(a){var b=a.U(),c=g.LF||g.hP?{style:"will-change: opacity"}:void 0,d=b.D,e=["ytp-videowall-still"];
b.B&&e.push("ytp-videowall-show-text");g.S.call(this,{I:"a",Ka:e,X:{href:"{{url}}",target:d?b.W:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},V:[{I:"div",S:"ytp-videowall-still-image",X:{style:"{{background}}"}},{I:"span",S:"ytp-videowall-still-info",X:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-info-bg",V:[{I:"span",S:"ytp-videowall-still-info-content",X:c,V:[{I:"span",S:"ytp-videowall-still-info-title",va:"{{title}}"},
{I:"span",S:"ytp-videowall-still-info-author",va:"{{author_and_views}}"},{I:"span",S:"ytp-videowall-still-info-live",va:"Tr\u1ef1c ti\u1ebfp"},{I:"span",S:"ytp-videowall-still-info-duration",va:"{{duration}}"}]}]}]},{I:"span",Ka:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-listlabel-icon"},"Danh s\u00e1ch ph\u00e1t",{I:"span",S:"ytp-videowall-still-listlabel-length",V:[" (",{I:"span",va:"{{playlist_length}}"},
")"]}]},{I:"span",Ka:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-listlabel-mix-icon"},"Tuy\u1ec3n t\u1eadp",{I:"span",S:"ytp-videowall-still-listlabel-length",va:" (50+)"}]}]});this.suggestion=null;this.B=d;this.api=a;this.j=new g.PF(this);g.P(this,this.j);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.j.T(a,"videodatachange",this.onVideoDataChange);a.createServerVe(this.element,
this);this.onVideoDataChange()},w5=function(a){p5.call(this,a,"videowall-endscreen");
var b=this;this.J=a;this.C=0;this.stills=[];this.D=this.videoData=null;this.G=this.N=!1;this.W=null;this.B=new g.PF(this);g.P(this,this.B);this.K=new g.gp(function(){g.op(b.element,"ytp-show-tiles")},0);
g.P(this,this.K);var c=new g.S({I:"button",Ka:["ytp-button","ytp-endscreen-previous"],X:{"aria-label":"Tr\u01b0\u1edbc"},V:[g.Gx()]});g.P(this,c);c.Ha(this.element);c.listen("click",this.r5,this);this.table=new g.wx({I:"div",S:"ytp-endscreen-content"});g.P(this,this.table);this.table.Ha(this.element);c=new g.S({I:"button",Ka:["ytp-button","ytp-endscreen-next"],X:{"aria-label":"Ti\u1ebfp theo"},V:[g.Hx()]});g.P(this,c);c.Ha(this.element);c.listen("click",this.q5,this);a.getVideoData().zf?this.j=new n5(a,
!0):this.j=new q5(a);g.P(this,this.j);g.DS(this.player,this.j.element,4);a.createClientVe(this.element,this,158789);this.hide()},x5=function(a){return g.HS(a.player)&&a.ME()&&!a.D},y5=function(a){var b=a.Hf();
b!==a.N&&(a.N=b,a.player.publish("autonavvisibility"))},z5=function(a){p5.call(this,a,"watch-again-on-youtube-endscreen");
this.watchButton=new t5(a,1);g.P(this,this.watchButton);this.watchButton.Ha(this.element);g.m$a(a)&&(this.j=new g.e1(a),g.P(this,this.j),this.B=new g.S({I:"div",Ka:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],X:{tabIndex:"-1"},V:[this.j]}),g.P(this,this.B),this.j.Ha(this.B.element),this.B.Ha(this.element));a.createClientVe(this.element,this,156914);this.hide()},Ckb=function(a){g.WX.call(this,a);
var b=this;this.endScreen=null;this.B=this.j=this.C=this.D=!1;this.listeners=new g.PF(this);g.P(this,this.listeners);var c=a.U(),d=a.getVideoData();d=d&&d.limitedPlaybackDurationInSeconds!==0;g.qs(g.sP(c))&&d&&!g.gS(a)?(this.B=!0,this.endScreen=new u5(a,g.RR(a))):a.fd()?this.endScreen=new z5(a):zkb(a)?(this.D=!0,Akb(this),this.j?this.endScreen=new r5(a):this.endScreen=new w5(a)):c.Fh?this.endScreen=new ykb(a):this.endScreen=new p5(a);g.P(this,this.endScreen);g.DS(a,this.endScreen.element,4);Bkb(this);
this.listeners.T(a,"videodatachange",this.onVideoDataChange,this);this.listeners.T(a,g.rE("endscreen"),function(e){b.onCueRangeEnter(e)});
this.listeners.T(a,g.sE("endscreen"),function(e){b.onCueRangeExit(e)})},Akb=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.xl&&a.C===b.zf)return!1;a.j=b.xl;a.C=b.zf;return!0},zkb=function(a){a=a.U();
return a.yd&&!a.Fh},Bkb=function(a){a.player.jf("endscreen");
var b=a.player.getVideoData();b=new g.pE(Math.max((b.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.pE(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.nf([b,c])};
g.cS.prototype.du=g.ba(14,function(){return this.app.du()});
g.K_.prototype.du=g.ba(13,function(){return this.getVideoData().D_});
g.ZR.prototype.Vs=g.ba(12,function(a){this.Li().Vs(a)});
g.SY.prototype.Vs=g.ba(11,function(a){this.j!==a&&(this.j=a,this.Ra())});
g.$Z.prototype.Vs=g.ba(10,function(a){this.overflowButton&&this.overflowButton.Vs(a)});
g.ZR.prototype.Ws=g.ba(9,function(a){this.Li().Ws(a)});
g.XY.prototype.Ws=g.ba(8,function(a){this.j!==a&&(this.j=a,this.Ra())});
g.$Z.prototype.Ws=g.ba(7,function(a){this.shareButton&&this.shareButton.Ws(a)});
g.ZR.prototype.IC=g.ba(6,function(a){this.Li().IC(a)});
g.vY.prototype.IC=g.ba(5,function(a){this.cT!==a&&(this.cT=a,this.xr())});
g.ZR.prototype.HC=g.ba(4,function(a){this.Li().HC(a)});
g.$Z.prototype.HC=g.ba(3,function(a){this.bT!==a&&(this.bT=a,this.wr())});g.z(m5,g.S);m5.prototype.select=function(){this.J.Fp(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.sF||void 0)&&this.J.logClick(this.element)};
m5.prototype.onClick=function(a){g.ZS(a,this.J,this.j,this.suggestion.sessionData||void 0)&&this.select()};
m5.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};g.z(n5,g.S);g.k=n5.prototype;g.k.QI=function(a){this.suggestion!==a&&(this.suggestion=a,l5(this.j,a),this.playButton.updateValue("url",this.suggestion.Ol()),o5(this))};
g.k.Vl=function(){return this.C>0};
g.k.SC=function(){this.Vl()||(this.C=Date.now(),skb(this),qkb(this.J,ukb(this)),g.sp(this.J.getRootNode(),"countdown-running",this.Vl()))};
g.k.Ny=function(){this.ir();skb(this);var a=this.j.Da("ytp-autonav-endscreen-upnext-header");a&&g.mh(a,"Ti\u1ebfp theo")};
g.k.ir=function(){this.Vl()&&(this.D.stop(),this.C=0)};
g.k.select=function(a){this.J.nextVideo(!1,a===void 0?!1:a);this.ir()};
g.k.vV=function(a){g.ZS(a,this.J)&&(a.currentTarget===this.playButton.element?this.J.logClick(this.playButton.element):a.currentTarget===this.j.Da("ytp-autonav-endscreen-link-container")&&(a=this.j.Da("ytp-autonav-endscreen-link-container"),this.J.logVisibility(a,!0),this.J.logClick(a)),this.J.L("web_player_autonav_next_button_renderer")&&this.G?(this.J.eb("innertubeCommand",this.G),this.ir()):this.select())};
g.k.l5=function(){this.J.logClick(this.cancelButton.element);g.eS(this.J,!0);this.cancelCommand&&this.J.eb("innertubeCommand",this.cancelCommand)};
g.k.onVideoDataChange=function(a,b){this.J.L("web_player_autonav_next_button_renderer")&&rkb(this,b);var c;this.cancelCommand=(c=b.N4)==null?void 0:c.command};
g.k.Waa=function(a){if(vkb(this)){var b=this.J.getVideoData().watchToWatchTransitionRenderer,c=b==null?void 0:b.fromColorPaletteDark;b=b==null?void 0:b.toColorPaletteDark;if(c&&b){var d=this.element;d.style.setProperty("--w2w-start-background-color",g.$y(c.surgeColor));d.style.setProperty("--w2w-start-primary-text-color",g.$y(c.primaryTitleColor));d.style.setProperty("--w2w-start-secondary-text-color",g.$y(c.secondaryTitleColor));d.style.setProperty("--w2w-end-background-color",g.$y(b.surgeColor));
d.style.setProperty("--w2w-end-primary-text-color",g.$y(b.primaryTitleColor));d.style.setProperty("--w2w-end-secondary-text-color",g.$y(b.secondaryTitleColor));d.style.setProperty("--w2w-animation-duration",a+"ms")}g.sp(this.element,"ytp-w2w-animate",!0)}};
g.k.k5=function(a){this.J.L("web_autonav_color_transition")&&a!==2&&g.sp(this.element,"ytp-w2w-animate",!1)};
g.k.uV=function(){var a=this.J.Hf();this.K&&this.Eb!==a&&g.zx(this,a);o5(this);this.J.logVisibility(this.container.element,a);this.J.logVisibility(this.cancelButton.element,a);this.J.logVisibility(this.j.Da("ytp-autonav-endscreen-link-container"),a);this.J.logVisibility(this.playButton.element,a)};
g.k.Sg=function(a){return a.width<400||a.height<459};g.z(p5,g.S);g.k=p5.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.ME=function(){return!1};
g.k.Hf=function(){return!1};
g.k.n_=function(){return!1};g.z(q5,g.S);g.k=q5.prototype;g.k.IJ=function(){this.notification&&(this.D.stop(),this.Lc(this.C),this.C=null,this.notification.close(),this.notification=null)};
g.k.QI=function(a){this.suggestion=a;l5(this,a,"hqdefault.jpg")};
g.k.wV=function(){g.zx(this,this.api.Hf());this.api.logVisibility(this.element,this.api.Hf());this.api.logVisibility(this.Da("ytp-upnext-autoplay-icon"),this.api.Hf());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.Hf())};
g.k.Uba=function(){window.focus();this.IJ()};
g.k.SC=function(a){var b=this;this.Vl()||(g.wv("a11y-announce","Ti\u1ebfp theo "+this.suggestion.title),this.B=(0,g.Kt)(),this.j=new g.gp(function(){xkb(b,a)},25),xkb(this,a),qkb(this.api,wkb(this,a)));
g.qp(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.S.prototype.hide.call(this)};
g.k.Vl=function(){return!!this.j};
g.k.Ny=function(){this.ir();this.B=(0,g.Kt)();xkb(this);g.op(this.element,"ytp-upnext-autoplay-paused")};
g.k.ir=function(){this.Vl()&&(this.j.dispose(),this.j=null)};
g.k.select=function(a){a=a===void 0?!1:a;if(this.api.U().L("autonav_notifications")&&a&&window.Notification&&typeof document.hasFocus==="function"){var b=Notification.permission;b==="default"?Notification.requestPermission():b!=="granted"||document.hasFocus()||(this.IJ(),this.notification=new Notification("Ti\u1ebfp theo",{body:this.suggestion.title,icon:this.suggestion.lh()}),this.C=this.T(this.notification,"click",this.Uba),this.D.start())}this.ir();this.api.nextVideo(!1,a)};
g.k.n5=function(a){!g.lh(this.cancelButton.element,a.target)&&g.ZS(a,this.api)&&(this.api.Hf()&&this.api.logClick(this.Da("ytp-upnext-autoplay-icon")),this.select())};
g.k.m5=function(){this.api.Hf()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.eS(this.api,!0)};
g.k.Lba=function(a){this.api.getPresentingPlayerType();this.show();this.SC(a)};
g.k.Mba=function(){this.api.getPresentingPlayerType();this.ir();this.hide()};
g.k.xa=function(){this.ir();this.IJ();g.S.prototype.xa.call(this)};g.z(r5,p5);g.k=r5.prototype;g.k.create=function(){p5.prototype.create.call(this);this.D.T(this.player,"appresize",this.DD);this.D.T(this.player,"onVideoAreaChange",this.DD);this.D.T(this.player,"videodatachange",this.onVideoDataChange);this.D.T(this.player,"autonavchange",this.xV);this.D.T(this.player,"onAutonavCancelled",this.o5);this.onVideoDataChange()};
g.k.show=function(){p5.prototype.show.call(this);(this.K||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.eS(this.player,!1);g.HS(this.player)&&this.ME()&&!this.C?(s5(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.j.select(!0):this.j.SC():this.videoData.autonavState===3&&this.j.Ny()):(g.eS(this.player,!0),s5(this));this.DD()};
g.k.hide=function(){p5.prototype.hide.call(this);this.j.Ny();s5(this)};
g.k.DD=function(){var a=this.player.Fo(!0,this.player.isFullscreen());s5(this);o5(this.B);g.sp(this.element,"ytp-autonav-cancelled-small-mode",this.Sg(a));g.sp(this.element,"ytp-autonav-cancelled-tiny-mode",this.lL(a));g.sp(this.element,"ytp-autonav-cancelled-mini-mode",a.width<=400||a.height<=360);this.overlay&&g.um(this.overlay.element,{width:a.width+"px"});if(!this.G)for(a=0;a<this.videos.length;a++)g.sp(this.videos[a].element,"ytp-suggestion-card-with-margin",a%2===1)};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length||this.player.L("web_player_autonav_empty_suggestions_fix")){var b=g.RQ(this.videoData);b&&(this.j.QI(b),this.j!==this.B&&this.B.QI(b))}if(a&&a.length)for(b=0;b<Dkb.length;++b){var c=Dkb[b];if(a&&a[c]){this.videos[b]=new m5(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,l5(d,c));g.P(this,this.videos[b]);this.videos[b].Ha(this.N.element)}}this.DD()}};
g.k.xV=function(a){a===1?(this.K=!1,this.C=this.videoData.clientPlaybackNonce,this.j.ir(),this.Eb&&this.DD()):(this.K=!0,this.Hf()&&(a===2?this.j.SC():a===3&&this.j.Ny()))};
g.k.o5=function(a){a?this.xV(1):(this.C=null,this.K=!1)};
g.k.ME=function(){return this.videoData.autonavState!==1};
g.k.Sg=function(a){return(a.width<910||a.height<459)&&!this.lL(a)&&!(a.width<=400||a.height<=360)};
g.k.lL=function(a){return a.width<800&&!(a.width<=400||a.height<=360)};
g.k.Hf=function(){return this.Eb&&g.HS(this.player)&&this.ME()&&!this.C};
var Dkb=[1,3,2,4];g.z(t5,g.S);g.k=t5.prototype;g.k.M2=function(){switch(this.buttonType){case 1:var a="Xem l\u1ea1i tr\u00ean YouTube";var b=156915;break;case 2:a="Ti\u1ebfp t\u1ee5c xem tr\u00ean YouTube";b=156942;break;default:a="Ti\u1ebfp t\u1ee5c xem tr\u00ean YouTube",b=156942}this.update({content:a});this.J.hasVe(this.element)&&this.J.destroyVe(this.element);this.J.createClientVe(this.element,this,b)};
g.k.onClick=function(a){this.J.L("web_player_log_click_before_generating_ve_conversion_params")&&this.J.logClick(this.element);g.$S(this.getVideoUrl(),this.J,a);this.J.L("web_player_log_click_before_generating_ve_conversion_params")||this.J.logClick(this.element)};
g.k.getVideoUrl=function(){var a=!0;switch(this.buttonType){case 1:a=!0;break;case 2:a=!1}a=this.J.getVideoUrl(a,!1,!1,!0);var b=this.J.U();if(g.jP(b)){var c={};g.jP(b)&&g.MR(this.J,"addEmbedsConversionTrackingParams",[c]);a=g.Wi(a,c)}return a};
g.k.logVisibility=function(){this.J.logVisibility(this.element,this.Eb&&this.Z)};
g.k.show=function(){g.S.prototype.show.call(this);this.logVisibility()};
g.k.hide=function(){g.S.prototype.hide.call(this);this.logVisibility()};
g.k.Kc=function(a){g.S.prototype.Kc.call(this,a);this.logVisibility()};g.z(u5,p5);u5.prototype.show=function(){this.player.getPlayerState()!==3&&(p5.prototype.show.call(this),this.Qe.HC(!0),this.Qe.Ws(!0),this.J.U().le||this.Qe.Vs(!0),this.J.logVisibility(this.element,!0),this.watchButton.Kc(!0))};
u5.prototype.hide=function(){p5.prototype.hide.call(this);this.Qe.HC(!1);this.Qe.Ws(!1);this.Qe.Vs(!1);this.J.logVisibility(this.element,!1);this.watchButton.Kc(!1)};g.z(ykb,p5);ykb.prototype.Ra=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.xm;var b=this.subscribeButton;a.subscribed?b.j():b.B()};g.z(v5,g.S);v5.prototype.select=function(){this.api.Fp(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.sF||void 0)&&this.api.logClick(this.element)};
v5.prototype.onClick=function(a){if(g.jP(this.api.U())&&this.api.L("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var b=this.suggestion.Ol(),c={};g.hS(this.api,c);b=g.Wi(b,c);g.$S(b,this.api,a)}else g.ZS(a,this.api,this.B,this.suggestion.sessionData||void 0)&&this.select()};
v5.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};
v5.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.U();this.B=a.Jf?!1:b.D};g.z(w5,p5);g.k=w5.prototype;g.k.create=function(){p5.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.Cr();this.B.T(this.player,"appresize",this.Cr);this.B.T(this.player,"onVideoAreaChange",this.Cr);this.B.T(this.player,"videodatachange",this.onVideoDataChange);this.B.T(this.player,"autonavchange",this.PN);this.B.T(this.player,"onAutonavCancelled",this.p5);a=this.videoData.autonavState;a!==this.W&&this.PN(a);this.B.T(this.element,"transitionend",this.jda)};
g.k.destroy=function(){g.Ks(this.B);g.kg(this.stills);this.stills=[];p5.prototype.destroy.call(this);g.qp(this.element,"ytp-show-tiles");this.K.stop();this.W=this.videoData.autonavState};
g.k.ME=function(){return this.videoData.autonavState!==1};
g.k.show=function(){var a=this.Eb;p5.prototype.show.call(this);g.qp(this.element,"ytp-show-tiles");this.player.U().B?g.ip(this.K):this.K.start();(this.G||this.D&&this.D!==this.videoData.clientPlaybackNonce)&&g.eS(this.player,!1);x5(this)?(y5(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.j.select(!0):this.j.SC():this.videoData.autonavState===3&&this.j.Ny()):(g.eS(this.player,!0),y5(this));a!==this.Eb&&this.player.logVisibility(this.element,!0)};
g.k.hide=function(){var a=this.Eb;p5.prototype.hide.call(this);this.j.Ny();y5(this);a!==this.Eb&&this.player.logVisibility(this.element,!1)};
g.k.jda=function(a){a.target===this.element&&this.Cr()};
g.k.Cr=function(){var a,b,c,d;var e=((a=this.videoData)==null?0:(b=a.suggestions)==null?0:b.length)?(c=this.videoData)==null?void 0:c.suggestions:[(d=this.videoData)==null?void 0:g.RQ(d)];if(e.length){g.op(this.element,"ytp-endscreen-paginate");var f=this.J.Fo(!0,this.J.isFullscreen());if(a=g.RR(this.J))a=a.Oh()?48:32,f.width-=a*2;var h=f.width/f.height;d=96/54;b=a=2;var l=Math.max(f.width/96,2),m=Math.max(f.height/54,2);c=e.length;var n=c*4;for(n-=4;n>0&&(a<l||b<m);){var p=a/2,q=b/2,r=a<=l-2&&n>=
q*4,t=b<=m-2&&n>=p*4;if((p+1)/q*d/h>h/(p/(q+1)*d)&&t)n-=p*4,b+=2;else if(r)n-=q*4,a+=2;else if(t)n-=p*4,b+=2;else break}d=!1;n>=12&&c*4-n<=6&&(b>=4||a>=4)&&(d=!0);n=a*96;l=b*54;h=n/l<h?f.height/l:f.width/n;h=Math.min(h,2);n=Math.floor(Math.min(f.width,n*h));l=Math.floor(Math.min(f.height,l*h));f=this.table.element;f.ariaLive="polite";g.Fm(f,n,l);g.um(f,{marginLeft:n/-2+"px",marginTop:l/-2+"px"});this.j.QI(g.RQ(this.videoData));this.j instanceof n5&&o5(this.j);g.sp(this.element,"ytp-endscreen-takeover",
x5(this));y5(this);n+=4;l+=4;h=0;f.ariaBusy="true";for(m=0;m<a;m++)for(p=0;p<b;p++)if(q=h,t=0,d&&m>=a-2&&p>=b-2?t=1:p%2===0&&m%2===0&&(p<2&&m<2?p===0&&m===0&&(t=2):t=2),q=g.qg(q+this.C,c),t!==0){r=this.stills[h];r||(r=new v5(this.player),this.stills[h]=r,f.appendChild(r.element));var u=Math.floor(l*p/b),y=Math.floor(n*m/a),A=Math.floor(l*(p+t)/b)-u-4,C=Math.floor(n*(m+t)/a)-y-4;g.Bm(r.element,y,u);g.Fm(r.element,C,A);g.um(r.element,"transitionDelay",(p+m)/20+"s");g.sp(r.element,"ytp-videowall-still-mini",
t===1);g.sp(r.element,"ytp-videowall-still-large",t>2);t=Math.max(C,A);g.sp(r.element,"ytp-videowall-still-round-large",t>=256);g.sp(r.element,"ytp-videowall-still-round-medium",t>96&&t<256);g.sp(r.element,"ytp-videowall-still-round-small",t<=96);q=e[q];r.suggestion!==q&&(r.suggestion=q,t=r.api.U(),u=g.np(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",l5(r,q,u),g.jP(t)&&!r.api.L("web_player_log_click_before_generating_ve_conversion_params")&&(t=q.Ol(),u={},g.MR(r.api,"addEmbedsConversionTrackingParams",
[u]),t=g.Wi(t,u),r.updateValue("url",t)),(q=(q=q.sessionData)&&q.itct)&&r.api.setTrackingParams(r.element,q));h++}f.ariaBusy="false";g.sp(this.element,"ytp-endscreen-paginate",h<c);for(e=this.stills.length-1;e>=h;e--)a=this.stills[e],g.kh(a.element),g.jg(a);this.stills.length=h}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData(1);this.videoData!==a&&(a!=null&&g.RQ(a)?(this.C=0,this.videoData=a,this.Cr()):this.player.ma("missg",{vid:(a==null?void 0:a.videoId)||"",cpn:(a==null?void 0:a.clientPlaybackNonce)||""}))};
g.k.q5=function(){this.C+=this.stills.length;this.Cr()};
g.k.r5=function(){this.C-=this.stills.length;this.Cr()};
g.k.n_=function(){return this.j.Vl()};
g.k.PN=function(a){a===1?(this.G=!1,this.D=this.videoData.clientPlaybackNonce,this.j.ir(),this.Eb&&this.Cr()):(this.G=!0,this.Eb&&x5(this)&&(a===2?this.j.SC():a===3&&this.j.Ny()))};
g.k.p5=function(a){if(a){for(a=0;a<this.stills.length;a++)this.J.logVisibility(this.stills[a].element,!0);this.PN(1)}else this.D=null,this.G=!1;this.Cr()};
g.k.Hf=function(){return this.Eb&&x5(this)};g.z(z5,p5);z5.prototype.show=function(){if(this.player.getPlayerState()!==3){p5.prototype.show.call(this);var a=this.B;if(a){var b=this.j.suggestionData.length>0;g.sp(this.element,"ytp-shorts-branded-ui",b);b?a.show():a.hide()}var c;(c=g.RR(this.player))==null||c.IC(!0);this.player.logVisibility(this.element,!0);this.watchButton.Kc(!0)}};
z5.prototype.hide=function(){p5.prototype.hide.call(this);var a;(a=g.RR(this.player))==null||a.IC(!1);this.player.logVisibility(this.element,!1);this.watchButton.Kc(!1)};g.z(Ckb,g.WX);g.k=Ckb.prototype;g.k.Gv=function(){var a=this.player.getVideoData(),b=a.mutedAutoplay;if((this.player.fd()||this.B)&&!b)return!0;var c;var d=!!((a==null?0:g.RQ(a))||(a==null?0:(c=a.suggestions)==null?0:c.length));d=!zkb(this.player)||d;a=a.Rj;c=this.player.FF();return d&&!a&&!c&&!b};
g.k.Hf=function(){return this.endScreen.Hf()};
g.k.I$=function(){return this.Hf()?this.endScreen.n_():!1};
g.k.xa=function(){this.player.jf("endscreen");g.WX.prototype.xa.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.transitionEndpointAtEndOfStream;if(b&&b.videoId){var c=this.player.yb().Je.get("heartbeat"),d=g.RQ(a);!d||b.videoId!==d.videoId||a.WW?(this.player.Fp(b.videoId,void 0,void 0,!0,!0,b),c&&c.uL("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0):a=!1}else a=!1;a||(g.WX.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.WX.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.Gv()&&(this.endScreen.created||this.endScreen.create(),a.getId()==="load"&&this.load())};
g.k.onCueRangeExit=function(a){a.getId()==="load"&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){Bkb(this);this.D&&Akb(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new r5(this.player):this.endScreen=new w5(this.player),g.P(this,this.endScreen),g.DS(this.player,this.endScreen.element,4))};g.VX("endscreen",Ckb);})(_yt_player);
