(function(g){var window=this;'use strict';var N5=function(a,b){g.S.call(this,{I:"button",Ka:["ytp-miniplayer-expand-watch-page-button","ytp-button","ytp-miniplayer-button-top-left"],X:{title:"{{title}}","data-tooltip-target-id":"ytp-miniplayer-expand-watch-page-button","aria-keyshortcuts":"i","data-title-no-tooltip":"{{data-title-no-tooltip}}"},V:[{I:"svg",X:{height:"24px",version:"1.1",viewBox:"0 0 24 24",width:"24px"},V:[{I:"g",X:{fill:"none","fill-rule":"evenodd",stroke:"none","stroke-width":"1"},V:[{I:"g",X:{transform:"translate(12.000000, 12.000000) scale(-1, 1) translate(-12.000000, -12.000000) "},
V:[{I:"path",X:{d:"M19,19 L5,19 L5,5 L12,5 L12,3 L5,3 C3.89,3 3,3.9 3,5 L3,19 C3,20.1 3.89,21 5,21 L19,21 C20.1,21 21,20.1 21,19 L21,12 L19,12 L19,19 Z M14,3 L14,5 L17.59,5 L7.76,14.83 L9.17,16.24 L19,6.41 L19,10 L21,10 L21,3 L14,3 Z",fill:"#fff","fill-rule":"nonzero"}}]}]}]}]});this.J=a;this.listen("click",this.onClick,this);this.updateValue("title",g.bS(a,"M\u1edf r\u1ed9ng","i"));this.update({"data-title-no-tooltip":"M\u1edf r\u1ed9ng"});this.addOnDisposeCallback(g.$R(b.Ue(),this.element))},zlb=
function(a){g.S.call(this,{I:"div",
S:"ytp-miniplayer-ui"});this.N=this.G=!1;this.player=a;this.T(a,"minimized",this.yh);this.T(a,"onStateChange",this.efa);this.T(a,"documentpictureinpicturechange",this.qba)},Alb=function(a,b){g.sp(a.player.getRootNode(),"ytp-player-minimized",b);
a.player.L("web_cairo_modern_miniplayer")&&g.sp(a.player.getRootNode(),"ytp-modern-miniplayer",b);a.player.L("web_cairo_modern_miniplayer_inset_progress_bar")&&g.sp(a.player.getRootNode(),"ytp-miniplayer-alternate-ui",b)},Blb=function(a){var b=a.player.ob().getPlayerSize().width,c=0,d=b;
if(a.player.L("web_cairo_modern_miniplayer")&&!a.N&&!a.player.L("web_cairo_modern_miniplayer_infobar")||a.player.L("web_cairo_modern_miniplayer_inset_progress_bar"))c=12,d=b-24;g.O3a(a.progressBar,c,d,!1);g.pZ(a.progressBar)},Clb=function(a){g.WX.call(this,a);
this.B=new g.PF(this);this.j=new zlb(this.player);this.j.hide();g.DS(this.player,this.j.element,4);a.isMinimized()&&(this.load(),g.sp(a.getRootNode(),"ytp-player-minimized",!0))};
g.z(N5,g.S);N5.prototype.onClick=function(){this.J.eb("onExpandMiniplayer")};g.z(zlb,g.S);g.k=zlb.prototype;
g.k.show=function(){this.j=new g.fp(this.w5,null,this);this.j.start();if(!this.G){this.tooltip=new g.ZZ(this.player,this);g.P(this,this.tooltip);g.DS(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.oe=new g.yY(this.player);g.P(this,this.oe);this.progressBar=new g.oZ(this.player,this);g.P(this,this.progressBar);g.DS(this.player,this.progressBar.element,4);this.player.L("web_cairo_modern_miniplayer_infobar")&&g.op(this.player.getRootNode(),"ytp-always-showing-infobar");this.B=new g.S({I:"div",
S:"ytp-miniplayer-scrim"});g.P(this,this.B);this.B.Ha(this.element);this.T(this.B.element,"click",this.Y0);var a=new g.S({I:"button",Ka:["ytp-miniplayer-close-button","ytp-button"],X:{"aria-label":"\u0110o\u0301ng"},V:[g.Ix()]});g.P(this,a);a.Ha(this.B.element);this.T(a.element,"click",this.zV);a=new N5(this.player,this);g.P(this,a);a.Ha(this.B.element);this.C=new g.S({I:"div",S:"ytp-miniplayer-controls"});g.P(this,this.C);this.C.Ha(this.B.element);this.player.L("web_cairo_modern_miniplayer")||this.T(this.C.element,
"click",this.Y0);var b=new g.S({I:"div",S:"ytp-miniplayer-button-container"});g.P(this,b);b.Ha(this.C.element);a=new g.S({I:"div",S:"ytp-miniplayer-play-button-container"});g.P(this,a);a.Ha(this.C.element);var c=new g.S({I:"div",S:"ytp-miniplayer-button-container"});g.P(this,c);c.Ha(this.C.element);this.W=new g.jZ(this.player,this,!1);g.P(this,this.W);this.W.Ha(b.element);b=new g.iZ(this.player,this);g.P(this,b);b.Ha(a.element);this.nextButton=new g.jZ(this.player,this,!0);g.P(this,this.nextButton);
this.nextButton.Ha(c.element);this.K=this.player.L("web_cairo_modern_miniplayer")?new g.SZ(this.player,this,0):new g.SZ(this.player,this);g.P(this,this.K);this.K.Ha(this.B.element);this.D=new g.S({I:"div",S:"ytp-miniplayer-buttons"});g.P(this,this.D);g.DS(this.player,this.D.element,4);a=new g.S({I:"button",Ka:["ytp-miniplayer-close-button","ytp-button"],X:{"aria-label":"\u0110o\u0301ng"},V:[g.Ix()]});g.P(this,a);a.Ha(this.D.element);this.T(a.element,"click",this.zV);a=new g.S({I:"button",Ka:["ytp-miniplayer-replay-button",
"ytp-button"],X:{"aria-label":"\u0110o\u0301ng"},V:[g.Ox()]});g.P(this,a);a.Ha(this.D.element);this.T(a.element,"click",this.wca);this.player.L("web_cairo_modern_miniplayer")&&(a=new N5(this.player,this),g.P(this,a),a.Ha(this.D.element));this.T(this.player,"presentingplayerstatechange",this.x5);this.T(this.player,"appresize",this.kc);this.T(this.player,"fullscreentoggled",this.kc);this.player.L("web_cairo_modern_miniplayer")&&this.T(this.player,"onPlaylistUpdate",this.KS);this.kc();this.G=!0}this.player.getPlayerState()!==
0&&g.S.prototype.show.call(this);this.progressBar.show();this.player.unloadModule("annotations_module")};
g.k.hide=function(){this.j&&(this.j.dispose(),this.j=void 0);g.S.prototype.hide.call(this);this.player.isMinimized()||(this.G&&this.progressBar.hide(),this.player.loadModule("annotations_module"))};
g.k.xa=function(){this.j&&(this.j.dispose(),this.j=void 0);g.S.prototype.xa.call(this)};
g.k.zV=function(){this.player.L("kevlar_watch_while_v2")||this.player.stopVideo();this.player.eb("onCloseMiniplayer")};
g.k.wca=function(){this.player.playVideo()};
g.k.Y0=function(a){if(a.target===this.B.element||a.target===this.C.element)this.player.getPlayerStateObject().isOrWillBePlaying()?this.player.pauseVideo():this.player.playVideo()};
g.k.yh=function(){Alb(this,this.player.isMinimized());this.player.L("web_cairo_modern_miniplayer")&&this.KS()};
g.k.qba=function(){Alb(this,this.player.gj());this.player.L("web_cairo_modern_miniplayer")&&this.KS();g.sp(this.player.getRootNode(),"ytp-player-document-picture-in-picture",this.player.gj())};
g.k.Eg=function(){this.progressBar.Rc();this.K.Rc()};
g.k.w5=function(){this.Eg();this.j&&this.j.start()};
g.k.x5=function(a){g.U(a.state,32)&&this.tooltip.hide()};
g.k.KS=function(){this.N=(this.player.isMinimized()||this.player.gj())&&!!this.player.getPlaylist();g.sp(this.player.getRootNode(),"ytp-has-playlist-data",this.N);Blb(this)};
g.k.kc=function(){Blb(this)};
g.k.efa=function(a){this.player.isMinimized()&&(a===0?this.hide():this.show())};
g.k.Ue=function(){return this.tooltip};
g.k.Py=function(a,b,c,d,e){var f=0,h=0,l=0,m=g.Gm(a);d=b&&(g.np(b,"ytp-prev-button")||g.np(b,"ytp-next-button"));if(b){c=g.np(b,"ytp-play-button");var n=g.np(b,"ytp-miniplayer-expand-watch-page-button");d?f=l=12:c?(b=g.Em(b,this.element),l=b.x,f=b.y-12):n&&(l=g.np(b,"ytp-miniplayer-button-top-left"),f=g.Em(b,this.element),b=g.Gm(b),l?(l=8,f=f.y+40):(l=f.x-m.width+b.width,f=f.y-20))}else l=c-m.width/2,h=25+(e||0);b=this.player.ob().getPlayerSize();e=f+(e||0);m=g.pg(l,0,b.width-m.width-12);e?(a.style.top=
e+"px",a.style.bottom=""):(a.style.top="",a.style.bottom=h+"px");a.style.left=m+"px";this.player.L("web_cairo_modern_miniplayer")&&(h=g.np(a,"ytp-preview"),a.style.visibility=d&&h&&b.height<225?"hidden":"")};g.z(Clb,g.WX);g.k=Clb.prototype;g.k.onVideoDataChange=function(){if(this.player.getVideoData()){var a=this.player.getVideoAspectRatio(),b=16/9;a=a>b+.1||a<b-.1;g.sp(this.player.getRootNode(),"ytp-rounded-miniplayer-not-regular-wide-video",a)}};
g.k.create=function(){g.WX.prototype.create.call(this);this.B.T(this.player,"videodatachange",this.onVideoDataChange);this.onVideoDataChange()};
g.k.Hn=function(){return!1};
g.k.load=function(){this.player.hideControls();this.j.show()};
g.k.unload=function(){this.player.showControls();this.j.hide()};g.VX("miniplayer",Clb);})(_yt_player);
